/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.jmmc.oimaging.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author martin
 */
public class TableEditorPanel extends javax.swing.JPanel {

    private final List<String> availableKeywords = new ArrayList<>();
    private final List<String> keywordsToDisplay = new ArrayList<>();

    private JDialog dialog;

    /**
     * Creates new form TableEditorPanel
     */
    public TableEditorPanel() {
        initComponents();
    }

    public TableEditorPanel(JDialog dialog, List<String> availableKeywordsKeywords) {
        initComponents();

        this.dialog = dialog;

        this.availableKeywords.addAll(availableKeywordsKeywords);
        for (String keyword : this.availableKeywords) {
            listAvailable.add(keyword);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonAdd = new javax.swing.JButton();
        jLabelDisplayed = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jLabelAvailable = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jPanelAvailable = new javax.swing.JPanel();
        jScrollPaneAvailable = new javax.swing.JScrollPane();
        listAvailable = new java.awt.List();
        jPanelDisplayed = new javax.swing.JPanel();
        jScrollPaneDisplayed = new javax.swing.JScrollPane();
        listDisplayed = new java.awt.List();
        jButtonRemove = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(400, 250));
        setLayout(new java.awt.GridBagLayout());

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(jButtonAdd, gridBagConstraints);

        jLabelDisplayed.setText("Keywords displayed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jLabelDisplayed, gridBagConstraints);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jButtonOk, gridBagConstraints);

        jLabelAvailable.setText("Available keywords");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabelAvailable, gridBagConstraints);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(jButtonCancel, gridBagConstraints);

        jPanelAvailable.setLayout(new java.awt.GridBagLayout());

        jScrollPaneAvailable.setViewportView(listAvailable);

        jPanelAvailable.add(jScrollPaneAvailable, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        add(jPanelAvailable, gridBagConstraints);

        jPanelDisplayed.setLayout(new java.awt.GridBagLayout());

        jScrollPaneDisplayed.setViewportView(listDisplayed);

        jPanelDisplayed.add(jScrollPaneDisplayed, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        add(jPanelDisplayed, gridBagConstraints);

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(jButtonRemove, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        listDisplayed.add(listAvailable.getSelectedItem());
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        listDisplayed.remove(listDisplayed.getSelectedItem());
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        keywordsToDisplay.addAll(Arrays.asList(listDisplayed.getItems()));
        dialog.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dialog.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public List<String> getKeywordsToDisplay() {
        return keywordsToDisplay;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelAvailable;
    private javax.swing.JLabel jLabelDisplayed;
    private javax.swing.JPanel jPanelAvailable;
    private javax.swing.JPanel jPanelDisplayed;
    private javax.swing.JScrollPane jScrollPaneAvailable;
    private javax.swing.JScrollPane jScrollPaneDisplayed;
    private java.awt.List listAvailable;
    private java.awt.List listDisplayed;
    // End of variables declaration//GEN-END:variables
}
