/** *****************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ***************************************************************************** */
package fr.jmmc.oimaging.gui;

import fr.jmmc.jmcs.gui.component.BasicTableSorter;
import fr.jmmc.jmcs.gui.util.SwingUtils;
import fr.jmmc.oiexplorer.core.gui.model.ColumnsTableModel;
import fr.jmmc.oimaging.model.ResultSetTableModel;
import fr.jmmc.oimaging.model.RatingCell;

import javax.swing.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import fr.jmmc.oimaging.model.ResultSetTableModelBis;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.Collections;

/**
 *
 * @author martin
 */
public class TablePanel extends javax.swing.JPanel {

    /**
     * ResultSet table model
     */
    private final ResultSetTableModelBis resultSetTableModelBis;

    /**
     * Creates new form TablePanel
     */
    public TablePanel() {

        // Build ResultsTable
        resultSetTableModelBis = new ResultSetTableModelBis();

        initComponents();

        BasicTableSorter resultSetTableSorter = new BasicTableSorter(resultSetTableModelBis, jResultSetTable.getTableHeader());
        jResultSetTable.setModel(resultSetTableSorter);
        SwingUtils.adjustRowHeight(jResultSetTable);

        jResultSetTable.setDefaultRenderer(jResultSetTable.getColumnClass(ResultSetTableModel.SUCCESS), new SuccessCell());

        final RatingCell ratingCell = new RatingCell();
        
        final TableColumn column = jResultSetTable.getColumn(resultSetTableModel.getColumnName(ResultSetTableModel.RATING));
        column.setCellRenderer(ratingCell);
        column.setCellEditor(ratingCell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResultSetTable = new javax.swing.JTable();
        jPanelTableOptions = new javax.swing.JPanel();
        jButtonShowTableEditor = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jResultSetTable.setModel(resultSetTableModelBis);
        jScrollPane1.setViewportView(jResultSetTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanelTableOptions.setLayout(new javax.swing.BoxLayout(jPanelTableOptions, javax.swing.BoxLayout.PAGE_AXIS));
        jSplitPane1.setLeftComponent(jPanelTableOptions);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jButtonShowTableEditor.setText("Table Editor");
        jButtonShowTableEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowTableEditorActionPerformed(evt);
            }
        });
        jPanelTableOptions.add(jButtonShowTableEditor, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

    public JTable getTable() {
        return this.jResultSetTable;
    }

    public ResultSetTableModelBis getTableModel() {
        return this.resultSetTableModelBis;
    }

    public void addControlComponent(JComponent component) {
        jPanelTableOptions.add(component);
    }

    /**
     * Display the table keywords editor and set the new headers
     */
    public void jButtonShowTableEditorActionPerformed(ActionEvent evt) {

        // Set the dialog box
        JOptionPane jOptionPane = new JOptionPane();
        JDialog dialog = jOptionPane.createDialog("Edit table headers");
        TableEditorPanel tableEditorPanel = new TableEditorPanel(dialog, resultSetTableModelBis.getHeaders());
        dialog.setContentPane(tableEditorPanel);
        dialog.setSize(400, 250);
        dialog.setVisible(true);

        // Get the new headers returned by the dialog box et redefine the table
        TableColumnModel resultSetTableColumnModel = jResultSetTable.getColumnModel();
        for (TableColumn column : Collections.list(resultSetTableColumnModel.getColumns())) {
            column.setMinWidth(0);
            column.setMaxWidth(0);
            column.setPreferredWidth(0);
            if (tableEditorPanel.getKeywordsToDisplay().contains((String) column.getHeaderValue())) {
                column.setMinWidth(0);
                column.setMaxWidth(1920 /*TODO: find a better way to get a less raw width */);
                column.sizeWidthToFit();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelTableOptions;
    private javax.swing.JTable jResultSetTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jButtonShowTableEditor;
    // End of variables declaration//GEN-END:variables

}
